# Generated by Django 5.2.8 on 2025-12-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0005_service_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(help_text='Generic/scientific name of the medicine', max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', help_text='Brand/trade name of the medicine', max_length=200)),
                ('strength', models.CharField(help_text='Strength/dosage (e.g., 500mg, 125mg/5ml)', max_length=50)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('gel', 'Gel'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('nasal_spray', 'Nasal Spray'), ('powder', 'Powder'), ('softgel', 'Softgel'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('solution', 'Solution'), ('lotion', 'Lotion'), ('nebule', 'Nebule')], help_text='Pharmaceutical form', max_length=20)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic/Pain Reliever'), ('antipyretic', 'Antipyretic/Fever Reducer'), ('antihistamine', 'Antihistamine'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antacid', 'Antacid/GI'), ('bronchodilator', 'Bronchodilator'), ('corticosteroid', 'Corticosteroid'), ('vitamin', 'Vitamin/Supplement'), ('nsaid', 'NSAID'), ('antiemetic', 'Antiemetic'), ('antidiarrheal', 'Antidiarrheal'), ('laxative', 'Laxative'), ('antifungal', 'Antifungal'), ('antiviral', 'Antiviral'), ('cardiovascular', 'Cardiovascular'), ('cns', 'CNS/Neurological'), ('dermatological', 'Dermatological'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic/Ear'), ('other', 'Other')], default='other', help_text='Medicine category', max_length=20)),
                ('default_sig', models.CharField(blank=True, default='', help_text='Default prescription instructions (Signa)', max_length=500)),
                ('default_quantity', models.PositiveIntegerField(blank=True, help_text='Default quantity to prescribe', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this medicine is currently available')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinic.clinic')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['generic_name', 'strength'],
                'unique_together': {('clinic', 'generic_name', 'strength', 'form')},
            },
        ),
    ]
