# Generated by Django 5.2.8 on 2025-12-01 12:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0005_service_duration_minutes'),
        ('consultations', '0004_remove_consultation_physical_exam_notes_and_more'),
        ('patients', '0003_patient_civil_status_patient_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.CharField(help_text='Unique invoice ID (e.g., INV-2025-0001)', max_length=20)),
                ('invoice_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items', max_digits=12)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('amount', 'Fixed Amount'), ('percent', 'Percentage')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount or percentage', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount after discount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time of payment', null=True)),
                ('payment_method', models.CharField(default='cash', help_text='Payment method (cash only for now)', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Receipt number or reference', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinic.clinic')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
                'unique_together': {('clinic', 'invoice_id')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Item description', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount (quantity × unit_price)', max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('service', models.ForeignKey(blank=True, help_text='Reference to service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='clinic.service')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
    ]
