# Generated by Django 5.2.8 on 2025-12-01 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0005_service_duration_minutes'),
        ('consultations', '0001_initial'),
        ('medicines', '0001_initial'),
        ('patients', '0003_patient_civil_status_patient_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_id', models.CharField(help_text='Unique prescription ID (e.g., RX-2025-0001)', max_length=20)),
                ('prescription_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True, default='', help_text='Diagnosis for this prescription')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or instructions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.clinic')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date', '-created_at'],
                'unique_together': {('clinic', 'prescription_id')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(help_text='Medicine name (generic + brand if applicable)', max_length=300)),
                ('strength', models.CharField(blank=True, default='', help_text='Strength/dosage (e.g., 500mg)', max_length=50)),
                ('form', models.CharField(blank=True, default='', help_text='Pharmaceutical form (e.g., Tablet, Capsule)', max_length=50)),
                ('sig', models.CharField(help_text='Prescription instructions (Signa)', max_length=500)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to dispense')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes for this medicine')),
                ('medicine', models.ForeignKey(blank=True, help_text='Reference to medicine in formulary (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'ordering': ['id'],
            },
        ),
    ]
