# Generated by Django 5.2.8 on 2025-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='differential_diagnoses',
            field=models.JSONField(blank=True, default=list, help_text='List of differential diagnoses to consider'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='primary_diagnosis',
            field=models.CharField(blank=True, default='', help_text='Primary/working diagnosis', max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='secondary_diagnoses',
            field=models.JSONField(blank=True, default=list, help_text='List of secondary diagnoses'),
        ),
    ]
