# Generated by Django 5.2.8 on 2025-12-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_differential_diagnoses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
    ]
