# Generated by Django 5.2.8 on 2025-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultation_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='physical_exam_notes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='physical_exam',
            field=models.JSONField(blank=True, default=dict, help_text='Physical exam findings by system: general, heent, neck, chest, cvs, abdomen, extremities, neuro'),
        ),
    ]
