# Generated by Django 5.2.8 on 2025-11-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '__first__'),
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='The clinic this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Whether this user is the clinic owner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Secretary', 'Secretary'), ('Cashier', 'Cashier')], default='Admin', help_text="User's role in the clinic", max_length=20),
        ),
    ]
