# Generated by Django 5.2.8 on 2025-11-30 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_clinic_description_remove_clinic_mobile_and_more'),
        ('users', '0003_customuser_clinic_customuser_is_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the role', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the role's responsibilities")),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('permissions', models.JSONField(default=list, help_text="List of permission codes (e.g., ['patients.view', 'billing.create'])")),
                ('color', models.CharField(default='#6b7280', help_text='Color for UI display (hex code)', max_length=20)),
                ('icon', models.CharField(default='User', help_text='Icon name for UI display', max_length=50)),
                ('clinic', models.ForeignKey(help_text='The clinic this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clinic.clinic')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('clinic', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The user who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='The role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(help_text='The user assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
