# Generated by Django 5.2.8 on 2025-11-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Permission code (e.g., 'patients.view')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'View Patients')", max_length=100)),
                ('category', models.CharField(help_text="Category for grouping (e.g., 'Patients', 'Billing')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin roles have full access to all features'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, help_text='DEPRECATED - Use RolePolicy instead'),
        ),
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='The policy attached to the role', on_delete=django.db.models.deletion.CASCADE, related_name='role_policies', to='users.policy')),
                ('role', models.ForeignKey(help_text='The role this policy is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='role_policies', to='users.role')),
            ],
            options={
                'unique_together': {('role', 'policy')},
            },
        ),
    ]
