# Generated by Django 5.2.8 on 2025-11-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address_city_patient_address_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
