# Generated by Django 5.2.8 on 2025-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='address_state',
            new_name='address_region',
        ),
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='tax_id',
            field=models.CharField(blank=True, help_text='TIN (Tax Identification Number)', max_length=20, null=True),
        ),
    ]
