# Generated by Django 5.2.8 on 2025-11-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rename_address_state_clinic_address_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='tax_id',
        ),
    ]
