# Generated by Django 5.2.8 on 2025-11-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Default duration in minutes'),
        ),
    ]
