# Generated by Django 5.2.8 on 2025-12-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0005_service_duration_minutes'),
        ('consultations', '0004_remove_consultation_physical_exam_notes_and_more'),
        ('patients', '0003_patient_civil_status_patient_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(help_text='Unique order ID (e.g., LAB-2025-0001)', max_length=20)),
                ('order_date', models.DateField(help_text='Date the order was created')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', help_text='Order priority', max_length=10)),
                ('clinical_indication', models.TextField(blank=True, default='', help_text='Clinical reason for ordering the tests')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('processing', 'Processing'), ('results_available', 'Results Available'), ('reviewed', 'Reviewed'), ('cancelled', 'Cancelled')], default='ordered', help_text='Current status of the order', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clinic.clinic')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='consultations.consultation')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-order_date', '-created_at'],
                'unique_together': {('clinic', 'order_id')},
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the lab test', max_length=200)),
                ('code', models.CharField(blank=True, default='', help_text='Test code (e.g., CBC, CMP)', max_length=50)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('urinalysis', 'Urinalysis'), ('microbiology', 'Microbiology'), ('imaging', 'Imaging'), ('cardiology', 'Cardiology'), ('other', 'Other')], default='other', help_text='Test category', max_length=20)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('sputum', 'Sputum'), ('csf', 'CSF'), ('none', 'None (Imaging)'), ('other', 'Other')], default='blood', help_text='Type of sample required', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the test')),
                ('turnaround_time', models.CharField(blank=True, default='', help_text='Expected turnaround time (e.g., 24-48 hours)', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the test', max_digits=10, null=True)),
                ('special_instructions', models.TextField(blank=True, default='', help_text='Default special instructions (e.g., fasting required)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is currently available')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='clinic.clinic')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['category', 'name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(help_text='Name of the test', max_length=200)),
                ('test_code', models.CharField(blank=True, default='', help_text='Test code', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Test category', max_length=50)),
                ('sample_type', models.CharField(blank=True, default='', help_text='Sample type required', max_length=50)),
                ('special_instructions', models.TextField(blank=True, default='', help_text='Special instructions for this test')),
                ('result', models.TextField(blank=True, default='', help_text='Test result')),
                ('result_date', models.DateTimeField(blank=True, help_text='Date/time when result was recorded', null=True)),
                ('is_abnormal', models.BooleanField(default=False, help_text='Whether the result is abnormal')),
                ('result_notes', models.TextField(blank=True, default='', help_text='Notes about the result')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_orders.laborder')),
                ('lab_test', models.ForeignKey(blank=True, help_text='Reference to test catalog (optional for historical preservation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='lab_orders.labtest')),
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
                'ordering': ['id'],
            },
        ),
    ]
