# Generated by Django 5.2.4 on 2025-09-05 07:49

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agent_type',
            field=models.CharField(blank=True, choices=apps.chat.models.get_agent_type_choices, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('agent', 'Agent')], default='chat', max_length=30),
        ),
    ]
